name: Days 4-5 CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t myapp:${{ github.sha }} .
    
    - name: Run tests
      run: |
        docker run --rm myapp:${{ github.sha }} python -m pytest tests/
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Push to Docker Hub
      run: |
        docker tag myapp:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/myapp:latest
    
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a ${{ secrets.HEROKU_APP_NAME }}
        heroku container:release web -a ${{ secrets.HEROKU_APP_NAME }}

    - name: Assignment Completion
      if: success()
      run: |
        echo "Congratulations! Your Days 4-5 assignment has been completed successfully."
        echo "You've set up a CI/CD pipeline for your application!"

    - name: Assignment Incomplete
      if: failure()
      run: |
        echo "It looks like there might be some issues with your CI/CD pipeline."
        echo "Please check the error messages above and make sure you've completed all parts of the assignment."
        echo "Don't hesitate to ask for help if you're stuck!"

